<?php

namespace AppBundle\Repository\Smartphones;

/**
 * AvisSmartphonesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvisSmartphonesRepository extends \Doctrine\ORM\EntityRepository
{
}
