<?php

namespace AppBundle\Repository\Smartphones;

/**
 * MarqueSmartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarqueSmartRepository extends \Doctrine\ORM\EntityRepository
{
}
