<?php

namespace AppBundle\Repository\Smartphones;

/**
 * MarquesSmartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarquesSmartRepository extends \Doctrine\ORM\EntityRepository
{
}
