<?php

namespace AppBundle\Repository\Smartphones;

/**
 * SmartphonesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SmartphonesRepository extends \Doctrine\ORM\EntityRepository
{

    public function getLastSmart()
    {

        return $this->createQueryBuilder('s')
            ->where('s.valide = true')
            ->orderBy('s.id', 'DESC')
            ->setMaxResults(2)
            ->getQuery()
            ->getResult();
    }
}
