<?php

namespace AppBundle\Repository;

/**
 * AvisServicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvisServicesRepository extends \Doctrine\ORM\EntityRepository
{
}
