<?php

namespace AppBundle\Repository;

/**
 * CategoriesServicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriesServicesRepository extends \Doctrine\ORM\EntityRepository
{
}
