<?php

namespace AppBundle\Repository;

/**
 * CategoriesProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriesProduitsRepository extends \Doctrine\ORM\EntityRepository
{
}
