<?php

namespace AppBundle\Repository\Tablettes;

/**
 * AvisTablettesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvisTablettesRepository extends \Doctrine\ORM\EntityRepository
{
}
