<?php

namespace AppBundle\Repository\Tablettes;

/**
 * MarquesTabletteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarquesTabletteRepository extends \Doctrine\ORM\EntityRepository
{
}
