<?php

namespace AppBundle\Repository\Tablettes;

/**
 * TablettesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TablettesRepository extends \Doctrine\ORM\EntityRepository
{
}
