<?php

namespace AppBundle\Repository\Informatique;

/**
 * AvisInformatiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvisInformatiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
