<?php

namespace AppBundle\Repository\Informatique;

/**
 * CategorieInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
