<?php

namespace AppBundle\Repository\Informatique;

/**
 * InformatiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformatiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
