<?php

namespace AppBundle\Repository\Informatique;

/**
 * InformatiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformatiqueRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastInfo()
    {
        return $this->createQueryBuilder('i')
            ->where('i.valide = true')
            ->orderBy('i.id', 'DESC')
            ->setMaxResults(2)
            ->getQuery()
            ->getResult()
            ;
    }
}
