<?php

namespace AppBundle\Repository\Informatique;

/**
 * MarqueInformatiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarqueInformatiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
