<?php

namespace AppBundle\Repository\Restaurants;

/**
 * AvisRestaurantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvisRestaurantsRepository extends \Doctrine\ORM\EntityRepository
{
}
