<?php

namespace AppBundle\Repository\Restaurants;

/**
 * RestaurantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantsRepository extends \Doctrine\ORM\EntityRepository
{


    public function getLastRestau()
    {
        return $this->createQueryBuilder('r')
            ->where('r.valide = true')
            ->orderBy('r.id', 'DESC')
            ->setMaxResults(2)
            ->getQuery()
            ->getResult()
            ;
    }


}
